logging:
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /pokeguide

spring:
    application:
        name: pokeGuide
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://3.34.158.6/pokeguide
        username: poke

    data:
        redis:
            host: localhost
            port: 6379

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    session:
        store-type: redis

    mail:
        host: smtp.gmail.com
        port: 587
        username: oharam0413@gmail.com
        password: xwov wdxm kafb vhun
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

file:
    upload:
        path: uploads/

img:
    upload:
        path: prodImg/

jwt:
    issuer: hyeji111544@gmail.com
    secret: 4XudNUpSmog3lwI9thJFejF7YfBBQnCI

front:
    #url: 'http://localhost:3000' # 개발용
    url: 'http://3.34.158.6' # 배포용



