name: Deploy to EC2 with Docker

on:
  push:
    branches: [ main ] # main branch로 push 될 때 실행

env:  
  DOCKER_IMAGE_NAME: mydockerhubusername/myapp
  EC2_HOST: ec2-3-34-158-6.ap-northeast-2.compute.amazonaws.com
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Docker 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:latest .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE_NAME:latest

      # EC2 배포
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            cd /home/ubuntu
            sudo docker pull $DOCKER_IMAGE_NAME:latest
            sudo docker-compose down
            sudo docker-compose up -d
          EOF
